import type { Metadata } from "next";
import { Montserrat, Exo_2 } from "next/font/google";
import "./globals.css";
import { CryptoProvider } from "./context/CriptoContext";



const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
})

const exo2 = Exo_2({
  variable: "--font-exo-2-sans",
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "StartCrypto",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${exo2.variable} ${montserrat.variable} antialiased text-branco `}
      >
        <CryptoProvider>
          {children}
        </CryptoProvider>

      </body>
    </html>
  );
}
